import { compile } from 'ass-compiler';

import { processDialogues } from './cue-processor';
import { IdGenerator } from './id-generator';
import { generateMetaHCL } from './meta-processor';
import { processStyles } from './style-processor';

export default function convertASStoESL(assContent: string): string {
    const compiledASS = compile(assContent, {});

    const motionIdGenerator = new IdGenerator();

    const metaHCL = generateMetaHCL(compiledASS.info);
    const { stylesHCL, processedStylesMap } = processStyles(compiledASS.styles);
    const { cuesHCL, motionsHCL, autoGeneratedStylesHCL } = processDialogues(
        compiledASS.dialogues,
        processedStylesMap,
        motionIdGenerator,
    );

    const finalEslContent = [metaHCL, stylesHCL, autoGeneratedStylesHCL, motionsHCL, cuesHCL]
        .filter(Boolean)
        .join('\n\n');

    return finalEslContent;
}
